name: corsac_base
version: 0.1.0-dev
description: Common utilities for Corsac projects
homepage: https://github.com/corsac-dart/base
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  dotenv: "^0.1.3+3"
  yaml: "^2.1.7"
  corsac_console:
    git: https://github.com/corsac-dart/console.git
  corsac_di:
    git: https://github.com/corsac-dart/di.git
  corsac_kernel:
    git: https://github.com/corsac-dart/kernel.git
  corsac_stateless:
    git:
      url: https://github.com/corsac-dart/stateless.git
      ref: refactor
  corsac_dto:
    git: https://github.com/corsac-dart/dto.git

dev_dependencies:
  test: "^0.12.6+1"
