name: corsac_base
version: 0.1.0-dev
description: Common utilities for Corsac projects
homepage: https://github.com/corsac-dart/base
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.9.0 <2.0.0'

dev_dependencies:
  test: "^0.12.6+1"
